################################## Layout #######################################
Layout/IndentHash:
  EnforcedStyle: consistent

Layout/SpaceInLambdaLiteral:
  EnforcedStyle: require_space

################################## Naming #######################################
Naming/FileName:
  Exclude:
    - 'lib/clevertap-ruby.rb'

################################## Style #######################################

Style/FormatString:
  EnforcedStyle: format

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/EmptyCaseCondition:
  Enabled: false

################################## Metrics #####################################

Metrics/AbcSize:
  Max: 120

Metrics/BlockLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 40

Metrics/LineLength:
  Max: 140

Metrics/MethodLength:
  Max: 70

Metrics/ModuleLength:
  Max: 200

Metrics/PerceivedComplexity:
  Max: 10
